name: CI

on: [push]
#  push:
#    branches:
#      - main
#      - develop
#    paths-ignore:
#      - Docs/**
#      - README.md
#      - LICENSE
#      - Rambafile
#  pull_request:
#    branches:
#      # - !main
#      - develop
#    paths-ignore:
#      - Docs/**
#      - README.md
#      - LICENSE
#      - Rambafile

env:
  DEVELOPER_DIR: /Applications/Xcode_13.1.app

jobs:
  build:
    runs-on: macos-11

    steps:
    # ソースコードを取得する
    - uses: actions/checkout@v1

    # Ruby製のライブラリをインストールする
    - name: Bundle install
      run: bundle install

    # ビルドする
    - name: Xcode build
      run: xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        build
        | bundle exec xcpretty

    # テストする
    - name: Xcode test
      run: xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -scheme aruaru-lt-mobile-9-demo
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
        -skip-testing:aruaru-lt-mobile-9-demoUITests
        clean test
        | bundle exec xcpretty --report html
        

  info:
    runs-on: macos-11

    steps:
    # チェックアウト
    - uses: actions/checkout@v2

    # Xcodeの一覧出力
    - name: Show Xcode list
      run: ls /Applications | grep 'Xcode'

    # Xcodeのバージョン出力
    - name: Show Xcode version
      run: xcodebuild -version

    # Makeのバージョン出力
    - name: Show Make version
      run: make --version

    # Rubyのバージョン出力
    - name: Show Ruby version
      run: ruby --version

    # Bundlerのバージョン出力
    - name: Show Bundler version
      run: bundle version

    # 端末の一覧出力
    - name: Show devices
      run: make show-devices
