name: CI
# githubActionPractice
on: [push] # git push をトリガーとする

#env:
#  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app



jobs:
  UnitTestResult:
    runs-on: macos-11 # 仮想環境指定（Windows Server, Ubuntu, Mac OSをサポートする）

    steps:
    # ソースコードを取得する
    - uses: actions/checkout@v1

    # キャッシュ
    - name: Cache CocoaPods files
      uses: actions/cache@v1
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    # CocoaPodsをインストールする
    - name: CocoaPods
      run: pod install

    # シミュレーター向けにビルド
    - name: Xcode UnitTest
      run: set -o pipefail &&
          xcodebuild
          -sdk iphonesimulator
          -configuration Debug
          -workspace githubActionPractice.xcworkspace
          -scheme githubActionPractice
          -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
          -skip-testing:githubActionPracticeUITests
          clean test | bundle exec xcpretty --report html

    # テストする
    # - name: Xcode test
    #   run: set -o pipefail &&
    #     xcodebuild
    #     -sdk iphonesimulator
    #     -configuration Debug
    #     -workspace githubActionPractice.xcworkspace
    #     -scheme githubActionPractice
    #     -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
    #     -skip-testing:githubActionPracticeUITests
    #     clean test
    #     | bundle exec xcpretty --report html


#
#  info:
#    runs-on: macos-11
#
#    steps:
#    # チェックアウト
#    - uses: actions/checkout@v2
#
#    # Xcodeの一覧出力
#    - name: Show Xcode list
#      run: ls /Applications | grep 'Xcode'
#
#    # Xcodeのバージョン出力
#    - name: Show Xcode version
#      run: xcodebuild -version
#
#    # Makeのバージョン出力
#    - name: Show Make version
#      run: make --version
#
#    # Rubyのバージョン出力
#    - name: Show Ruby version
#      run: ruby --version
#
#    # Bundlerのバージョン出力
#    - name: Show Bundler version
#      run: bundle version
#
#    # 端末の一覧出力
#    - name: Show devices
#      run: xcrun xctrace list devices
