name: CI

on: [push] # git push をトリガーとする

jobs:
  build:
    runs-on: macos-11
    
    steps:
    # ソースコードを取得する
    - uses: actions/checkout@v1
    
    # ビルドする
    - name: Select Xcode version # Xcode 12.4 を使う
      run: sudo xcode-select -s '/Applications/Xcode_13.1.app/Contents/Developer'
    
    - name: Show Xcode version
      run: xcodebuild -version
      
    # シミュレーター向けにビルド
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build

#    # CocoaPods
#    - name: CocoaPods
#      run: pod install
#    - name: Xcode build
#      run: xcodebuild
#        -sdk iphonesimulator
#        -configuration Debug
#        build
#        | bundle exec xcpretty

#    # テストする
#    - name: Xcode test
#      run: xcodebuild
#        -sdk iphonesimulator
#        -configuration Debug
#        -scheme aruaru-lt-mobile-9-demo
#        -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
#        -skip-testing:aruaru-lt-mobile-9-demoUITests
#        clean test
#        | bundle exec xcpretty --report html
