name: CI

on: [push] # git push をトリガーとする

jobs:
    build:
    
    runs-on: macos-latest
    
    steps:
    # ソースコードを取得する
    - uses: actions/checkout@v1
    
    # ビルドする
    - name: Xcode build
      run: xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        build
        | bundle exec xcpretty

#    # テストする
#    - name: Xcode test
#      run: xcodebuild
#        -sdk iphonesimulator
#        -configuration Debug
#        -scheme aruaru-lt-mobile-9-demo
#        -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
#        -skip-testing:aruaru-lt-mobile-9-demoUITests
#        clean test
#        | bundle exec xcpretty --report html
