name: CI

on: [push] # git push をトリガーとする

#env:
#  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app

jobs:
  build:
    name: XcodeUnitTest   # job 名
    runs-on: macos-11     # 仮想環境指定（Windows Server, Ubuntu, Mac OSをサポートする）
      
    steps:
    
    # ソースコードを取得する
    - uses: actions/checkout@v2
    
    - name: Select Xcode version # Xcode 12.4 を使う
      run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    
    - name: Drivedata
      run: rm -rf ~/Library/Developer/Xcode/DerivedData/*
      
    # CocoaPodsをインストールする
    - name: CocoaPods
      run: pod install
#      run: rm -rf ~/Library/Caches/CocoaPods/ | rm -rf Pods | pod install

    - name: Cache CocoaPods files
      uses: actions/cache@preview
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    
    - name: Build # シミュレーター向けにビルド
      run: xcodebuild -sdk iphonesimulator -configuration Debug build


#    # ビルドする
#    - name: Xcode build
#      run: xcodebuild
#        -sdk iphonesimulator
#        -configuration Debug
#        build
#        | bundle exec xcpretty
#
#    # テストする
#    - name: Xcode test
#      run: set -o pipefail &&
#        xcodebuild
#        -sdk iphonesimulator
#        -configuration Debug
#        -workspace githubActionPractice.xcworkspace
#        -scheme githubActionPractice
#        -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
#        -skip-testing:githubActionPracticeUITests
#        clean test
#        | bundle exec xcpretty --report html
        

#
#  info:
#    runs-on: macos-11
#
#    steps:
#    # チェックアウト
#    - uses: actions/checkout@v2
#
#    # Xcodeの一覧出力
#    - name: Show Xcode list
#      run: ls /Applications | grep 'Xcode'
#
#    # Xcodeのバージョン出力
#    - name: Show Xcode version
#      run: xcodebuild -version
#
#    # Makeのバージョン出力
#    - name: Show Make version
#      run: make --version
#
#    # Rubyのバージョン出力
#    - name: Show Ruby version
#      run: ruby --version
#
#    # Bundlerのバージョン出力
#    - name: Show Bundler version
#      run: bundle version
#
#    # 端末の一覧出力
#    - name: Show devices
#      run: xcrun xctrace list devices
